name: MP CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: yarn

    - name: Build weapp
      run: yarn build

    # 从 secrets.UPLOAD_PRIVATE_KEY 生成私钥文件
    # see Project/Settings/Secrets
    - name: Generate private key for upload
      run: echo "$UPLOAD_PRIVATE_KEY" > private.key
      env:
        WXAPP_PRIVATE_KEY: ${{ secrets.WXAPP_PRIVATE_KEY }}
    # 上传代码
    - name: Preview to generate QR code
      run: yarn miniprogram-ci preview --pp ./dist/ --pkp ./private.key --appid wxc326b824cc3d1077 --uv V1.0.0
